# Default values for merbridge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# some settings of merbridge when start up
fullname: merbridge
namespace: istio-system
mode: istio
ipsFilePath: /host/ips/ips.txt
cniMode: false
debug: false

# some settings of deployment
image:
  hub: ghcr.io
  repository: merbridge/merbridge
  # Overrides the image tag whose default is the latest version.
  tag: latest
  pullPolicy: Always
resources:
  container:
    limit:
      cpu: 300m
      memory: 200Mi
    request:
      cpu: 100m
      memory: 200Mi
  init:
    limit:
      cpu: 300m
      memory: 50Mi
    request:
      cpu: 100m
      memory: 50Mi
mountPath:
  proc: /host/proc
  cniBin: /host/opt/cni/bin
  cniConfig: /host/etc/cni/net.d
  varRun: /host/var/run
dnsPolicy: ClusterFirst
revisionHistoryLimit: 10
